import test from "node:test";
import assert from "node:assert/strict";

import {
  extractAffectedUserIds,
  buildNetworkSyncPlan,
} from "../../../domain/network/PlayerNetworkStatsSynchronizer.js";


const A =
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAA";

const B =
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBB";

const C =
  "CCCCCCCCCCCCCCCCCCCCCCCCCCCC";

const D =
  "DDDDDDDDDDDDDDDDDDDDDDDDDDDD";


test(
  "extractAffectedUserIds unions before and after participants",
  () => {
    const validUsers =
      new Set([
        A,
        B,
        C,
      ]);

    const affected =
      extractAffectedUserIds(
        {
          createurUid: A,
          participants: [
            A,
            B,
          ],
        },
        {
          createurUid: A,
          participants: [
            A,
            C,
          ],
        },
        {
          validUserIds:
            validUsers,
        },
      );

    assert.deepEqual(
      [...affected].sort(),
      [
        A,
        B,
        C,
      ].sort(),
    );
  },
);


test(
  "extractAffectedUserIds ignores placeholders and unknown users",
  () => {
    const validUsers =
      new Set([
        A,
      ]);

    const affected =
      extractAffectedUserIds(
        null,
        {
          createurUid: A,
          participants: [
            A,
            "ami_de_A_1",
            D,
          ],
        },
        {
          validUserIds:
            validUsers,
        },
      );

    assert.deepEqual(
      [...affected],
      [
        A,
      ],
    );
  },
);


test(
  "buildNetworkSyncPlan upserts only affected current users",
  () => {
    const matches = [
      {
        createurUid: A,
        participants: [
          A,
          B,
        ],
        placeId: "place_1",
        dateHeure: 1000,
      },
      {
        createurUid: C,
        participants: [
          C,
          A,
        ],
        placeId: "place_2",
        dateHeure: 2000,
      },
    ];

    const plan =
      buildNetworkSyncPlan({
        matches,

        validUserIds:
          new Set([
            A,
            B,
            C,
          ]),

        affectedUserIds:
          new Set([
            A,
            B,
          ]),

        generatedAtMs:
          9000,
      });

    assert.deepEqual(
      plan.deletes,
      [],
    );

    assert.deepEqual(
      plan.upserts.map(
        (row) => row.uid,
      ),
      [
        A,
        B,
      ],
    );

    const a =
      plan.upserts.find(
        (row) =>
          row.uid === A,
      );

    assert.equal(
      a.matchesPlayed,
      2,
    );

    assert.equal(
      a.uniquePadimaPlayersSeen,
      2,
    );

    assert.equal(
      a.generatedAtMs,
      9000,
    );
  },
);


test(
  "buildNetworkSyncPlan deletes stale projection when user has no remaining stats",
  () => {
    const plan =
      buildNetworkSyncPlan({
        matches: [],

        validUserIds:
          new Set([
            A,
          ]),

        affectedUserIds:
          new Set([
            A,
          ]),

        generatedAtMs:
          5000,
      });

    assert.deepEqual(
      plan.upserts,
      [],
    );

    assert.deepEqual(
      plan.deletes,
      [
        A,
      ],
    );
  },
);


test(
  "historical deleted creator can influence current participant without getting a projection",
  () => {
    const historicalCreator =
      "HISTORICAL_FIREBASE_UID_123456";

    const plan =
      buildNetworkSyncPlan({
        matches: [
          {
            createurUid:
              historicalCreator,

            participants: [
              historicalCreator,
              A,
            ],

            dateHeure:
              1000,
          },
        ],

        validUserIds:
          new Set([
            A,
          ]),

        affectedUserIds:
          new Set([
            A,
          ]),

        generatedAtMs:
          2000,
      });

    assert.equal(
      plan.upserts.length,
      1,
    );

    assert.equal(
      plan.upserts[0].uid,
      A,
    );

    assert.equal(
      plan.upserts.some(
        (row) =>
          row.uid === historicalCreator,
      ),
      false,
    );
  },
);


test(
  "no score or badge is generated by synchronization",
  () => {
    const plan =
      buildNetworkSyncPlan({
        matches: [
          {
            createurUid: A,
            participants: [
              A,
              B,
            ],
          },
        ],

        validUserIds:
          new Set([
            A,
            B,
          ]),

        affectedUserIds:
          new Set([
            A,
          ]),
      });

    const row =
      plan.upserts[0];

    assert.equal(
      Object.hasOwn(
        row,
        "connectorScore",
      ),
      false,
    );

    assert.equal(
      Object.hasOwn(
        row,
        "badge",
      ),
      false,
    );
  },
);
